### PR TITLE
2021 Spring Cleaning

### PR DESCRIPTION
**Pull request by ntenczar**
Does a few things to spruce up the project
- eliminates wercker in favor of circleci
- updates circle to allow it to upload results to coveralls
- update readme badges to reflect all that
- adds dialyxir to the project and runs the dialyzer in CI
- removes a redundant typespec
- removes documentation regarding starting the `:exconstructor`
  application
- adds formatting and format checking (same checks as the rest of our stuff)
- stopped using our fork of `ex_spec` for the latest version `2.0.1`

### CODE REVIEW

**Review by humberaquino — APPROVED** [review]
Sweet! 🎖️

**Comment by jonathanhood** [comment]
Unfortunately, this PR now requires dialyxer to be deployed into our production environment. As a result, we've been forced to pin back this library to an older version.

@ntenczar Is it possible to change these CI dependencies for your library to be `only: [:dev]`  or similiar?

**Comment by ntenczar** [comment]
ah! I actually meant to do that, good find. I'll cut another release in a few

**Comment by ntenczar** [comment]
thanks for noticing!

**Pull request merged**
